WITH
 ----------------------------------------------------------------------------------------------
 -- BLOCO 1: ANÁLISE DE DESEMPENHO DE KPIS
 ----------------------------------------------------------------------------------------------
 DADOS_COM_RANK AS (
   SELECT
     SITE_ID, FACILITY_ID, KPI_NAME, YEAR, WEEK_NUMBER, DATE_VALUE, VALUE, NUMERADOR, DENOMINADOR, TARGET, ARROW,
     DENSE_RANK() OVER(PARTITION BY SITE_ID, FACILITY_ID, KPI_NAME ORDER BY YEAR DESC, WEEK_NUMBER DESC) AS WEEK_RANK
   FROM `meli-sbox.ICQACENTRAL.DM_SHP_MUK_KPI_REPORT_ICQA_PH` AS C
   INNER JOIN `meli-bi-data.WHOWNER.LK_SHP_FACILITIES` AS F
     ON F.SHP_FACILITY_ID = C.FACILITY_ID AND F.SHP_FACILITY_TYPE = 'warehouse' AND F.SHP_STATUS = 'active'
   WHERE
     UNIT = 'WEEK' AND KPI_NAME IN ('UFF Operativo')
     AND FACILITY_ID NOT IN ('MXCD03') AND TARGET > 0
     AND DATE_VALUE BETWEEN DATE_SUB(DATE_TRUNC(CURRENT_DATE(), WEEK(SUNDAY)), INTERVAL 2 WEEK) AND DATE_SUB(DATE_TRUNC(CURRENT_DATE(), WEEK(SUNDAY)), INTERVAL 1 DAY)
 ),
 DADOS_PIVOTADOS AS (
   SELECT
     SITE_ID, FACILITY_ID, KPI_NAME,
     MAX(IF(WEEK_RANK = 1, YEAR, NULL)) AS ANO_W1, MAX(IF(WEEK_RANK = 1, WEEK_NUMBER, NULL)) AS SEMANA_W1,
     MAX(IF(WEEK_RANK = 1, DATE_VALUE, NULL)) AS DATA_REFERENCIA_W1, MAX(IF(WEEK_RANK = 1, ARROW, NULL)) AS ARROW_W1,
     MAX(IF(WEEK_RANK = 1, VALUE, NULL)) AS VALOR_W1, MAX(IF(WEEK_RANK = 1, TARGET, NULL)) AS TARGET_W1,
     MAX(IF(WEEK_RANK = 1, NUMERADOR, NULL)) AS NUMERADOR_W1, MAX(IF(WEEK_RANK = 1, DENOMINADOR, NULL)) AS DENOMINADOR_W1,
     MAX(IF(WEEK_RANK = 2, VALUE, NULL)) AS VALOR_W2, MAX(IF(WEEK_RANK = 2, NUMERADOR, NULL)) AS NUMERADOR_W2,
     MAX(IF(WEEK_RANK = 2, DENOMINADOR, NULL)) AS DENOMINADOR_W2
   FROM DADOS_COM_RANK
   GROUP BY SITE_ID, FACILITY_ID, KPI_NAME
 ),
 DADOS_COM_METRICAS AS (
   SELECT
     P.*, (P.VALOR_W1 - P.TARGET_W1) AS DISTANCIA_ABSOLUTA_META,
     (P.VALOR_W1 - P.TARGET_W1) * P.DENOMINADOR_W1 AS IMPACTO_ABSOLUTO_NUMERADOR,
     SAFE_DIVIDE(P.NUMERADOR_W1 - P.NUMERADOR_W2, P.NUMERADOR_W2) AS VARIACAO_NUMERADOR,
     SAFE_DIVIDE(P.DENOMINADOR_W1 - P.DENOMINADOR_W2, P.DENOMINADOR_W2) AS VARIACAO_DENOMINADOR,
     SAFE_DIVIDE(P.VALOR_W1 - P.VALOR_W2, P.VALOR_W2) AS VARIACAO_W1_VS_W2,
     SAFE_DIVIDE(P.VALOR_W1, P.TARGET_W1) - 1 AS PERCENTUAL_W1_VS_TARGET,
     CASE
       WHEN (P.ARROW_W1 = 'UP' AND P.VALOR_W1 < P.VALOR_W2 AND P.VALOR_W1 < P.TARGET_W1) OR (P.ARROW_W1 = 'DOWN' AND P.VALOR_W1 > P.VALOR_W2 AND P.VALOR_W1 > P.TARGET_W1) THEN 'Crítico'
       WHEN (P.ARROW_W1 = 'UP' AND P.VALOR_W1 > P.VALOR_W2 AND P.VALOR_W1 >= P.TARGET_W1) OR (P.ARROW_W1 = 'DOWN' AND P.VALOR_W1 < P.VALOR_W2 AND P.VALOR_W1 <= P.TARGET_W1) THEN 'Bom'
       ELSE 'Atenção'
     END AS CLASSIFICACAO_DESEMPENHO
   FROM DADOS_PIVOTADOS AS P
 ),
 DADOS_RANKEADOS AS (
   SELECT
     M.*, ROW_NUMBER() OVER(
       PARTITION BY M.SITE_ID, M.KPI_NAME
       ORDER BY CASE M.CLASSIFICACAO_DESEMPENHO WHEN 'Crítico' THEN 1 WHEN 'Atenção' THEN 2 WHEN 'Bom' THEN 3 ELSE 4 END,
       CASE WHEN M.ARROW_W1 = 'UP' THEN M.DISTANCIA_ABSOLUTA_META END ASC,
       CASE WHEN M.ARROW_W1 = 'DOWN' THEN M.DISTANCIA_ABSOLUTA_META END DESC
     ) AS RANK_PIOR_DESEMPENHO
   FROM DADOS_COM_METRICAS AS M
 ),
 DADOS_L10W AS (
   WITH DADOS_HISTORICOS AS (
     SELECT
       SITE_ID, FACILITY_ID, KPI_NAME, YEAR, WEEK_NUMBER, VALUE,
       DENSE_RANK() OVER(PARTITION BY SITE_ID, FACILITY_ID, KPI_NAME ORDER BY YEAR DESC, WEEK_NUMBER DESC) AS WEEK_RANK_HISTORICO
     FROM `meli-sbox.ICQACENTRAL.DM_SHP_MUK_KPI_REPORT_ICQA_PH`
     WHERE UNIT = 'WEEK' AND KPI_NAME IN ('UFF Operativo')
   )
   SELECT
     SITE_ID, FACILITY_ID, KPI_NAME,
     STRING_AGG(CONCAT('W', WEEK_NUMBER, ' - ', CAST(VALUE AS STRING)), ', ' ORDER BY YEAR, WEEK_NUMBER) AS L10W
   FROM DADOS_HISTORICOS WHERE WEEK_RANK_HISTORICO <= 10
   GROUP BY SITE_ID, FACILITY_ID, KPI_NAME
 ),

 ----------------------------------------------------------------------------------------------
 -- BLOCO 2: ANÁLISE UFF
 ----------------------------------------------------------------------------------------------
 ANALISE_UFF AS (
    WITH
 DADOS_BASE_CUSTO AS (
SELECT
SITE AS WAREHOUSE_ID,FECHA,SKU,CATEGORIA, TIPO_ORDEN, SUM(PIEZAS) PIEZAS
FROM meli-sbox.ICQACENTRAL.UFFDET as A
WHERE
1=1
AND FECHA BETWEEN DATE_SUB(DATE_TRUNC(CURRENT_DATE(), WEEK(SUNDAY)), INTERVAL 1 WEEK) AND DATE_SUB(DATE_TRUNC(CURRENT_DATE(), WEEK(SUNDAY)), INTERVAL 1 DAY)
GROUP BY ALL
 ),
 UFF_POR_SKU AS (
   SELECT WAREHOUSE_ID, SKU AS detalhe, SUM(PIEZAS) AS PIEZAS_TOTAL
   FROM DADOS_BASE_CUSTO GROUP BY WAREHOUSE_ID, detalhe
 ),
 UFF_POR_CATEGORIA AS (
   SELECT WAREHOUSE_ID, CATEGORIA AS detalhe, SUM(PIEZAS) AS PIEZAS_TOTAL
   FROM DADOS_BASE_CUSTO GROUP BY WAREHOUSE_ID, detalhe
 ),
 UFF_POR_TIPO AS (
   SELECT WAREHOUSE_ID, TIPO_ORDEN AS detalhe, SUM(PIEZAS) AS PIEZAS_TOTAL
   FROM DADOS_BASE_CUSTO  GROUP BY WAREHOUSE_ID, detalhe
 ),
 SKU_COM_RANK AS (
   SELECT WAREHOUSE_ID, detalhe, PIEZAS_TOTAL,
     RANK() OVER (PARTITION BY WAREHOUSE_ID ORDER BY PIEZAS_TOTAL DESC) AS rank,
     ROUND(PIEZAS_TOTAL / SUM(PIEZAS_TOTAL) OVER (PARTITION BY WAREHOUSE_ID), 4) AS participacao
   FROM UFF_POR_SKU
 ),
 CATEGORIAS_COM_RANK AS (
   SELECT WAREHOUSE_ID, detalhe, PIEZAS_TOTAL,
     RANK() OVER (PARTITION BY WAREHOUSE_ID ORDER BY PIEZAS_TOTAL DESC) AS rank,
     ROUND(PIEZAS_TOTAL / SUM(PIEZAS_TOTAL) OVER (PARTITION BY WAREHOUSE_ID), 4) AS participacao
   FROM UFF_POR_CATEGORIA
 ),
 TIPOS_COM_RANK AS (
   SELECT WAREHOUSE_ID, detalhe, PIEZAS_TOTAL,
     RANK() OVER (PARTITION BY WAREHOUSE_ID ORDER BY PIEZAS_TOTAL DESC) AS rank,
     ROUND(PIEZAS_TOTAL / SUM(PIEZAS_TOTAL) OVER (PARTITION BY WAREHOUSE_ID), 4) AS participacao
   FROM UFF_POR_TIPO
 ),
 SKUS_AGREGADOS AS (
   SELECT WAREHOUSE_ID, ARRAY_AGG(STRUCT(rank, detalhe, PIEZAS_TOTAL, participacao) ORDER BY rank) AS TOP_3_SKUS
   FROM SKU_COM_RANK WHERE rank <= 3 GROUP BY WAREHOUSE_ID
 ),
 CATEGORIAS_AGREGADAS AS (
   SELECT WAREHOUSE_ID, ARRAY_AGG(STRUCT(rank, detalhe, PIEZAS_TOTAL, participacao) ORDER BY rank) AS TOP_3_CATEGORIAS
   FROM CATEGORIAS_COM_RANK WHERE rank <= 3 GROUP BY WAREHOUSE_ID
 ),
 TIPOS_AGREGADAS AS (
   SELECT WAREHOUSE_ID, ARRAY_AGG(STRUCT(rank, detalhe, PIEZAS_TOTAL, participacao) ORDER BY rank) AS TOP_3_TIPOS
   FROM TIPOS_COM_RANK WHERE rank <= 3 GROUP BY WAREHOUSE_ID
 )
 SELECT
   WAREHOUSE_IDS.WAREHOUSE_ID, S.TOP_3_SKUS, C.TOP_3_CATEGORIAS, T.TOP_3_TIPOS
 FROM (SELECT DISTINCT WAREHOUSE_ID FROM DADOS_BASE_CUSTO) AS WAREHOUSE_IDS
 LEFT JOIN SKUS_AGREGADOS AS S ON WAREHOUSE_IDS.WAREHOUSE_ID = S.WAREHOUSE_ID
 LEFT JOIN CATEGORIAS_AGREGADAS AS C ON WAREHOUSE_IDS.WAREHOUSE_ID = C.WAREHOUSE_ID
 LEFT JOIN TIPOS_AGREGADAS AS T ON WAREHOUSE_IDS.WAREHOUSE_ID = T.WAREHOUSE_ID
 ORDER BY WAREHOUSE_IDS.WAREHOUSE_ID
 ),

 ----------------------------------------------------------------------------------------------
 -- NOVO BLOCO 4: ANÁLISE DE PERFORMANCE DE VENDAS POR CATEGORIA
 ----------------------------------------------------------------------------------------------
 ANALISE_PERFORMANCE_VENDAS AS (
   WITH
   DADOS_VENDAS_WOW AS (
      SELECT
       WAREHOUSE_ID,
       SEMANA,
       CAT_CATEG_NAME_L1,
       TOTAL_VENDAS,
       RANKING,
       LAG(TOTAL_VENDAS, 1, 0) OVER (PARTITION BY WAREHOUSE_ID, CAT_CATEG_NAME_L1 ORDER BY SEMANA) AS VENDAS_SEMANA_ANTERIOR
     FROM `meli-sbox.ICQACENTRAL.DM_SHP_ICQA_TOP_10_CATEG_L1_OUT`
   ),
   CALCULO_FINAL_VENDAS AS (

     SELECT
       WAREHOUSE_ID,
       SEMANA,
       CAT_CATEG_NAME_L1,
       RANKING,
       TOTAL_VENDAS,
       VENDAS_SEMANA_ANTERIOR,
       CASE
         WHEN VENDAS_SEMANA_ANTERIOR = 0 THEN 0
         ELSE SAFE_DIVIDE(TOTAL_VENDAS - VENDAS_SEMANA_ANTERIOR, VENDAS_SEMANA_ANTERIOR)
       END AS VARIACAO_PERCENTUAL,
       DENSE_RANK() OVER(PARTITION BY WAREHOUSE_ID ORDER BY SEMANA DESC) as week_rank_vendas
     FROM DADOS_VENDAS_WOW
   )

   SELECT
     WAREHOUSE_ID,
     ARRAY_AGG(
       STRUCT(
         RANKING,
         CAT_CATEG_NAME_L1,
         TOTAL_VENDAS,
         VENDAS_SEMANA_ANTERIOR,
         VARIACAO_PERCENTUAL
       )
       ORDER BY RANKING
       LIMIT 3
     ) AS TOP_3_PERFORMANCE_VENDAS
   FROM CALCULO_FINAL_VENDAS
   WHERE week_rank_vendas = 2
   GROUP BY WAREHOUSE_ID
 )

----------------------------------------------------------------------------------------------
-- ETAPA FINAL: JUNTAR ANÁLISE DE KPI, CUSTO E PERFORMANCE DE VENDAS
----------------------------------------------------------------------------------------------
SELECT
 R.SITE_ID, R.KPI_NAME, R.FACILITY_ID, R.RANK_PIOR_DESEMPENHO, R.CLASSIFICACAO_DESEMPENHO,
 R.VALOR_W1, R.TARGET_W1, R.ARROW_W1, R.NUMERADOR_W1, R.NUMERADOR_W2, R.DENOMINADOR_W1, R.DENOMINADOR_W2,
 R.DISTANCIA_ABSOLUTA_META, R.IMPACTO_ABSOLUTO_NUMERADOR, R.VARIACAO_NUMERADOR, R.VARIACAO_DENOMINADOR,
 R.PERCENTUAL_W1_VS_TARGET, R.VARIACAO_W1_VS_W2, R.VALOR_W2, R.SEMANA_W1, R.DATA_REFERENCIA_W1,
 H.L10W,
 UFF.TOP_3_SKUS, UFF.TOP_3_CATEGORIAS, UFF.TOP_3_TIPOS,
 VENDAS.TOP_3_PERFORMANCE_VENDAS,

 "" AS INSIGHT
FROM DADOS_RANKEADOS AS R
INNER JOIN DADOS_L10W AS H
 ON R.SITE_ID = H.SITE_ID AND R.FACILITY_ID = H.FACILITY_ID AND R.KPI_NAME = H.KPI_NAME
INNER JOIN ANALISE_UFF AS UFF
 ON R.FACILITY_ID = UFF.WAREHOUSE_ID AND R.KPI_NAME = 'UFF Operativo'
LEFT JOIN ANALISE_PERFORMANCE_VENDAS AS VENDAS
 ON R.FACILITY_ID = VENDAS.WAREHOUSE_ID
WHERE
 R.RANK_PIOR_DESEMPENHO <= 5
ORDER BY
 R.SITE_ID, R.KPI_NAME, R.RANK_PIOR_DESEMPENHO;